import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { getInvoice } from "../../api/invoiceApi";
import AlertMessage from "../../components/AlertMessage";
import { money, invoiceBadge } from "./InvoiceList";
import type { Invoice } from "../../types/invoice";

export default function InvoiceView() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [inv, setInv] = useState<Invoice | null>(null);
  const [alert, setAlert] = useState({ type: "", message: "" });

  useEffect(() => {
    getInvoice(Number(id)).then(r => setInv(r.data)).catch((e: any) => setAlert({ type: "danger", message: e.message }));
  }, [id]);

  if (!inv) return <div className="container py-4"><AlertMessage {...alert} onClose={() => setAlert({ type: "", message: "" })} />Loading…</div>;
  const b = inv.billing_snapshot || {};

  return (
    <div className="container py-4">
      <div className="d-flex gap-2 mb-3 d-print-none">
        <button className="btn btn-primary" onClick={() => window.print()}>Print</button>
        <button className="btn btn-secondary" onClick={() => navigate(-1)}>Back</button>
      </div>
      <div className="bg-white p-4 border rounded" style={{ maxWidth: 800, margin: "0 auto" }} id="invoice-card">
        <div className="d-flex justify-content-between align-items-start">
          <div>
            <h3 className="mb-0">TAX INVOICE</h3>
            <div className="text-muted">{inv.invoice_number}</div>
          </div>
          <span className={`badge bg-${invoiceBadge(inv.status)} fs-6`}>{inv.status.toUpperCase()}</span>
        </div>
        <hr />
        <div className="row">
          <div className="col-6">
            <div className="text-muted small">Billed to</div>
            <div className="fw-semibold">{b.name || inv.company_name}</div>
            <div className="small">{[b.address, b.city, b.state, b.pincode].filter(Boolean).join(", ")}</div>
            {b.gst_number && <div className="small">GSTIN: {b.gst_number}</div>}
          </div>
          <div className="col-6 text-end small">
            <div>Issue date: <strong>{inv.issue_date}</strong></div>
            <div>Due date: <strong>{inv.due_date}</strong></div>
            <div>Period: <strong>{inv.period_start} → {inv.period_end}</strong></div>
            {inv.paid_at && <div>Paid: <strong>{new Date(inv.paid_at).toLocaleDateString()}</strong>{inv.payment_ref ? ` (${inv.payment_ref})` : ""}</div>}
          </div>
        </div>
        <table className="table mt-4">
          <thead><tr><th>Description</th><th className="text-end">Qty</th><th className="text-end">Unit price</th><th className="text-end">Amount</th></tr></thead>
          <tbody>
            {inv.lines.map(l => (
              <tr key={l.id}>
                <td>{l.description}</td>
                <td className="text-end">{Number(l.quantity)}</td>
                <td className="text-end">{money(l.unit_price, inv.currency)}</td>
                <td className="text-end">{money(l.amount, inv.currency)}</td>
              </tr>
            ))}
          </tbody>
          <tfoot>
            <tr><td colSpan={3} className="text-end">Subtotal</td><td className="text-end">{money(inv.subtotal, inv.currency)}</td></tr>
            <tr><td colSpan={3} className="text-end">GST @ {Number(inv.tax_rate)}%</td><td className="text-end">{money(inv.tax_amount, inv.currency)}</td></tr>
            <tr className="fw-bold"><td colSpan={3} className="text-end">Total</td><td className="text-end">{money(inv.total, inv.currency)}</td></tr>
          </tfoot>
        </table>
        <p className="text-muted small mb-0">Generated by EcoNetVision ERP. This is a computer-generated invoice.</p>
      </div>
    </div>
  );
}
